version: "3.9"
services:
  backend-nginx:
    build:
      context: backend/docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/la-service
    depends_on:
      - backend-php-fpm
  backend-php-fpm:
    build:
      context: backend/docker
      dockerfile: php-fpm/Dockerfile
    environment:
      APPLICATION_ENVIRONMENT: development
      APPLICATION_DEBUG: 1
      MYSQL_HOST: backend-mysql
      MYSQL_USER: la-service
      MYSQL_PASSWORD: la-service
      MYSQL_DATABASE: la-service
      MYSQL_CHARSET: utf8
      MAILER_HOST: backend-mailer
      MAILER_PORT: 1025
      MAILER_USERNAME: alex
      MAILER_PASSWORD: 123
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: mail@app.test
      MAILER_FROM_NAME: test
      FRONTEND_URL: http://127.0.0.1
    volumes:
      - ./backend:/la-service
  backend-php-cli:
    build:
      context: backend/docker
      dockerfile: php-cli/Dockerfile
    environment:
     APPLICATION_ENVIRONMENT: development
     APPLICATION_DEBUG: 1
     MYSQL_HOST: backend-mysql
     MYSQL_USER: la-service
     MYSQL_PASSWORD: la-service
     MYSQL_DATABASE: la-service
     MYSQL_CHARSET: utf8
     MAILER_HOST: backend-mailer
     MAILER_PORT: 1025
     MAILER_USERNAME: alex
     MAILER_PASSWORD: 123
     MAILER_ENCRYPTION: tcp
     MAILER_FROM_EMAIL: mail@app.test
     MAILER_FROM_NAME: test
     FRONTEND_URL: http://127.0.0.1
    volumes:
      - ./backend:/la-service
  backend-mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: la-service
      MYSQL_PASSWORD: la-service
      MYSQL_ROOT_PASSWORD: la-service
      MYSQL_DATABASE: la-service
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  backend-mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  frontend-nginx:
    build:
      context: frontend/docker
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend-node
  frontend-node:
    build:
      context: frontend/docker
      dockerfile: node/Dockerfile
    environment:
      WDS_SOCKET_PORT: 0
    volumes:
      - ./frontend:/la-service
    command: npm start
    tty: true
  frontend-node-cli:
    build:
      context: frontend/docker
      dockerfile: node/Dockerfile
    volumes:
      - ./frontend:/la-service
volumes:
  mysql: