---
- name: la-service
  hosts: la-service
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: user
      tags: user
    - role: php
      tags: php
    - role: composer
      tags: composer
    - role: project
      tags: project
    - role: nginx
      tags: nginx
    - role: nginx-host-backend
      tags: nginx-host-backend
    - role: mysql
      tags: mysql
    - role: mysql-settings
      tags: mysql-settings
    - role: mysql-add-data
      tags: mysql-add-data
    - role: nodejs
      tags: nodejs
    - role: deploy
      tags: deploy