---
- name: la-service
  hosts: la-service
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: user
      tags: user
    - role: php
      tags: php
    - role: composer
      tags: composer
    - role: project
      tags: project