---
- name: settings for project
  block:
    - name: create main web directory
      file:
        path: "/var/www"
        state: directory
        owner: "www-data"
        group: "www-data"
        recurse: no
      debugger: on_failed
      tags: create main dir on project
    - name: create directory project
      file:
        path: "{{ dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: no
        mode: "0775"
      debugger: on_failed
      tags: project-install-soft
    - name: install soft project
      apt:
        name: git
        update_cache: yes
        state: present
      debugger: on_failed
      tags: install-soft-project
    - name: clone repo
      git:
        repo: "{{ repo }}"
        dest: "{{ dir }}"
        clone: yes
        update: no
      debugger: on_failed
      become: yes
      become_user: "{{ user }}"
      tags: clone-repo
  tags: project