---
- name: user management
  block:
    - name: create project user
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      debugger: on_failed
      tags: create-project-user
    - name: change mode www-data user
      user:
        name: www-data
        groups: "{{ user_name }}"
      debugger: on_failed
      tags: change-mode-www-data
  tags: user