name: la-service pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            # Делаем какую-то подготовительную работу типа тесты и линтеры
            - name:
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.PRODUCTION_KEY }}
                  known_hosts: ${{ secrets.PRODUCTION_HOST }}
              if: ${{ github.ref == 'refs/heads/main' }}
            - name:
              run: make deploy
              env:
                  HOST: ${{ secrets.PRODUCTION_HOST }}
                  PORT: ${{ secrets.PRODUCTION_PORT }}
              if: ${{ github.ref == 'refs/heads/main' }}