name: la-service pipeline
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            # Делаем какую-то подготовительную работу типа тесты и линтеры

            - name: deploy on server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  port: ${{ secrets.REMOTE_PORT }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  passphrase: ''
                  script: |
                    whoami
                    ls -al
