name: la-service pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout project
      uses: actions/checkout@v1
    # Подготовительная работа к деплою phpunit, linter, тесты и прочее и последнее что надо сделать это вылить на прод
    - name: push on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script_stop: true
        script: |
          git -C ${{ secrets.REMOTE_PATH }} pull
          composer install --working-dir=${{ secrets.REMOTE_PATH }} --no-dev --optimize-autoloader --classmap-authoritative