name: la-service pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1']
    steps:
      - name: Git checkout placeholder-service
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v2
          extensions: mbstring
      - name: Check PHP Version
        run: php -v
      - name: pwd
        run: pwd
      #  run: composer install --working-dir=${{ secrets.REMOTE_PATH }}/backend/
      #- name: Run test
      #  run: php ${{ secrets.REMOTE_PATH }}/backend/vendor/bin/phpunit test
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout project
      uses: actions/checkout@v2
    # Подготовительная работа к деплою phpunit, linter, тесты и прочее и последнее что надо сделать это вылить на прод
    - name: push on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script_stop: true
        script: |
          git -C ${{ secrets.REMOTE_PATH }} pull
          composer install --working-dir=${{ secrets.REMOTE_PATH }}/backend/ --no-dev --optimize-autoloader --classmap-authoritative